### ISSUE TITLE
במסופון התקבל להוסיף טבל

### ISSUE THREAD

**Issue by noam-honig** [noam-honig/mithashvim-maabada#1]
במסך "התקבל" נדרש לייצר טבלה בחלק שמאל של המסך מלמעלה למטה שמרכזת את כל הקליטות שבוצעו , הטבלה תכלול: תאריך, מקור התרומה, כמות מחשבים. בדרך זו בכל רגע נתון איש המלאי יוכל להבין כמה מתוך המחשבי שמולו הוא קלט למערכת.

מצ"ב תרשים
![image](https://user-images.githubusercontent.com/16635859/191673446-ff1f61f9-5c6a-4723-8b0a-ca1d2e08ac4c.png)

כנראה שהדרך היא להגדיר backendMethod שאוספת את המידע - ולהחזיר אותה לדפדפן.

ואת זה להציג
טבלת COMPUTERS
שדות:
origin
createDate

סינון
סטטוס שונה מ:
intakeTrash
trash

**Comment by noam-honig** [comment]
- [ ] 1. Bug - quantity only 1 - and not more
- [ ]  auto refresh
- [ ] Only show in "new " status

**Comment by shiraluk** [comment]
Closing
