### ISSUE TITLE
דשבורד סטטוס מלאי

### ISSUE THREAD

**Issue by shiraluk** [noam-honig/mithashvim-maabada#16]
דשבורד סטטוס מלאי
 
מלבד המסכים כיום נרצה לייצר 
 דשבורד פשוט שמציג עבור כל סטטוס - מה הכמות שיש ממנו כרגע
 ודרך לעשות דריל דאון מכל קטגוריה, ולראות ממש את הרשימה המתרעננת, מסוננת לפי הסטטוס שממנו הוא הגיע
כל מנהל (מלאי, אריזה שדרוג) רואה רק את הסטטוסים שלו
 
הסטטוסים של **מנהל מלאי** - כל הסטטוסים
 
 
![Image](https://user-images.githubusercontent.com/10912057/200281328-efb805b8-7d0f-4755-bd9b-169be4956aca.png)

 
 
**רש"צ שדרוג -** 
אותו דבר, עם הסטטוסים -
ממתין לשדרוג
שוייך לעובד
ממתין לגריטה
שודרג בהצלחה
 

 

![Image](https://user-images.githubusercontent.com/10912057/200281344-3d9afa39-9cee-4e16-a287-83ef7992d33f.png)

 
**רש"צ אריזה -** 
אותו דבר, עם הסטטוסים -
ממתין לאריזה
תהליך אריזה
נארז בהצלחה

![Image](https://user-images.githubusercontent.com/10912057/200281361-06e44d74-d275-474a-b7ed-e05d380dbd44.png)

**Comment by shiraluk** [comment]
הדשבורדים של רשצ אריזה ורשצ שדרוג לא מציגים את כל השדות שצריך

**דשבורד אריזה**

כרגע מכיל:
תהליך אריזה

צריך להכיל:
ממתין לאריזה
תהליך אריזה
נארז בהצלחה

**דשבורד שדרוג**

כרגע מכיל:
שוייך לעובד
ממתין לגריטה
שודרג בהצלחה

צריך להכיל:
ממתין לשדרוג
שוייך לעובד
ממתין לגריטה
שודרג בהצלחה


צילומי מסך של הקיים


![Image](https://user-images.githubusercontent.com/10912057/201520943-68c6b4bd-eb6e-4484-862f-ac6ec8ad9049.png)



![Image](https://user-images.githubusercontent.com/10912057/201520949-94ed155a-5fc2-404a-9c72-92d33817c951.png)

**Comment by noam-honig** [comment]
חשבתי שזה לפי ההרשאות שלהם :)

**Comment by shiraluk** [comment]
לא, הם צריכים לראות קצת יותר רוחבית
בינתיים אני רואה בפרודקשן שזה עדיין לא מעודכן, אולי לא דחפת את השינוי?
בכל מקרה מעבירה לטודו
