### ISSUE TITLE
רוצים לאפשר "צליפה ברצף" של ברקודים, ואז עדכון בבת אחת - בוא נעשה בריינסטורמינג אם זה אפשרי

### ISSUE THREAD

**Issue by shiraluk** [noam-honig/mithashvim-maabada#18]
במסופונים "התקבל" ו"התקבל וממתין לריטה"
העבודה הפיזית שם זה צליפה ברצף של משטח מלא מחשבים
היום הם צריכים לצלוף ואז ללחוץ על הכפתור "עדכן" במסופון וזה מאט את העבודה
רוצים חוויה כמו בסופר - צליפה רצופה, שהמערכת תקלוט את כל הברקודים, ואז רק עדכון
היום הם עושים את זה שני אנשים - אחד צולף ואחד נותן אנטר במערכת..

בוא נחשוב ביחד מה הדרך הכי קלה לאפשר את זה

**Comment by noam-honig** [comment]
אפשרות אחת היא כאשר הוקלדו 7 תוים, ללחוץ אוטומטית על עדכן
