### ISSUE TITLE
מסופון "ממתין לשינוע למוטב" - להוסיף טבלה מצד שמאל כמו במסופון "התקבל"

### ISSUE THREAD

**Issue by shiraluk** [noam-honig/mithashvim-maabada#25]
טבלה היסטורית אגרגטיבית שמראה לכל יום שתי עמודות
מוטב
מספר מחשבים

![Image](https://user-images.githubusercontent.com/10912057/201526383-bd928a81-52d8-46ad-8924-657cce28f5c2.png)

**Comment by shiraluk** [comment]
באג?

אני רואה מחשבים בסטטוס "ממתין לשינוע למוטב", אבל הטבלה משמאל ריקה



![Image](https://user-images.githubusercontent.com/10912057/202910896-9915a905-7405-44ca-8413-7dacdbbf9d19.png)



![Image](https://user-images.githubusercontent.com/10912057/202910909-39cd6e8f-d678-46a4-a751-5888c8da6f0a.png)

**Comment by noam-honig** [comment]
ההגדרה היא שהמערכת מציגה סטטוסים מ7 ימים אחורה - גם כאן
