### ISSUE TITLE
"ספירת ציוד מתרומה" - צריך לדבר בעל פה ואסביר את הפיצר - האפיון נמצא בפיגמה

### ISSUE THREAD

**Issue by shiraluk** [noam-honig/mithashvim-maabada#32]
האפיון כאן:

https://www.figma.com/file/FBjMHvD2vWM4Dg6FfpP7WE/%D7%9E%D7%AA%D7%97%D7%A9%D7%91%D7%99%D7%9D?node-id=524%3A1073&t=u86ztt3Wpv62d3c9-4

**Comment by operationsmitchashvim** [comment]
לק"י,
נועם אודה לסיועך
