### ISSUE TITLE
שינויים לטבלה במסך תהליך אריזה

### ISSUE THREAD

**Issue by operationsmitchashvim** [noam-honig/mithashvim-maabada#33]
אני רוצה שבמקום שם העובד (בטבלה מצד שמאל) יופיע ברקוד אריזה, וברקוד משטח

![image](https://user-images.githubusercontent.com/119286016/204216607-f207b1dc-4464-4b0d-8df0-97b790e66458.png)

**Comment by noam-honig** [comment]
Done
