### ISSUE TITLE
קליטת מחשבים ניידים

### ISSUE THREAD

**Issue by shiraluk** [noam-honig/mithashvim-maabada#34]
רוצים לקלוט מחשבים ניידים במפעל המשקם
הם מתנהגים טיפה אחרת - יש להם דגם ויצרן

צריך ליצור שני מסופונים חדשים של "התקבל - מחשב נייד" ו"התקבל וממתין לגריטה - מחשב נייד" - עם השדות המתאימים.
דגם הוא שדה טקסט פתוח
יצרן הוא שדה מרשימה סגורה, שכתובה בפיגמה

המסופונים המקוריים של קליטה צריכים לשנות את שם המסופון ואת שמות הסטטוסים של המחשבים
התקבל הופך להיות "התקבל - מחשב נייח"
התקבל וממתין לגריטה הופך להיות "התקבל וממתין לגריטה - מחשב נייח"

תיאורים של המסכים נמצאים בפיגמה:
https://www.figma.com/file/FBjMHvD2vWM4Dg6FfpP7WE/%D7%9E%D7%AA%D7%97%D7%A9%D7%91%D7%99%D7%9D?node-id=557%3A764&t=iiN1mTpqeehwLuWl-4

**Comment by noam-honig** [comment]
הוספתי IMOJE אחרת כל ההדבל בין נייח לנייד זה אות אחת בסוף משפט של 20 אותיות


![Image](https://user-images.githubusercontent.com/16635859/204339085-80586249-7e70-4a98-a45f-9f955b217c96.png)
