### ISSUE TITLE
הפרדת יצרנים במסך התקבל מחשב נייד

### ISSUE THREAD

**Issue by operationsmitchashvim** [noam-honig/mithashvim-maabada#35]
לק"י
נועם שלום,
אבקש להפריד בין שלושת היצרנים האחרונים  על מנת שלא יופיעו בשורה אחת
![image](https://user-images.githubusercontent.com/119286016/204363159-4be87c26-d8b4-4ea3-840d-ae288ee14cc2.png)

בתודה
גבריאל

**Comment by noam-honig** [comment]
fixed - will be deployed in 5 min
