### ISSUE TITLE
שורה שלמה שנדרש למחוק מה-DB

### ISSUE THREAD

**Issue by operationsmitchashvim** [noam-honig/mithashvim-maabada#36]
לק"י
הי נועם,
אני לא מצליח למחוק לגמרי את השורה הזו, תוכל לסייע
![image](https://user-images.githubusercontent.com/119286016/205505744-fbd1b61a-95a2-4320-b64e-cc5b3301b17d.png)

**Comment by noam-honig** [comment]
בגדול אני לא רוצה לאפשר מחיקה כדי שתעוד  לא ילכו לאיבוד.

מה אתה אומר?

**Comment by operationsmitchashvim** [comment]
מסכים ולכן רק אתה תעשה את זה

אחרת זה טופס את הברקוד

**Comment by noam-honig** [comment]
במסך מחשבים אתה יכול ליעדכן את הברקוד למשהו אחר? זה גם יפנה אותו.

**Comment by operationsmitchashvim** [comment]
הי נועם,
לדעתי הפתרון המושכל על מנת לא למחוק את המידע ומצד שני שהמידע לא יעיק הוא להעניק סטאטוס "**ברקוד נקלט בטעות**" רק על ידי בר המחליף שלי עם היוזר שלו ולא אחד העובדים

**Comment by noam-honig** [comment]
הלכתי על פתרון אחר - הוספתי אפשרות של מחיקה של מחשב - זה לא באמת מוחק, רק מסמן אותו כמחוק ומתעלם ממנו בכל השליפות

**Comment by noam-honig** [comment]
אח"כ אפשר בטבלה הגדיר הצג גם מחוקים כדי לראות גם מחוקים

**Comment by operationsmitchashvim** [comment]
מעולה, מחקתי את 505928
