### ISSUE TITLE
כפילות בר קוד מחשב במסך שודרג בהצלחה

### ISSUE THREAD

**Issue by operationsmitchashvim** [noam-honig/mithashvim-maabada#37]
לק"י
נועם שלום,
משום מה יש כפילותבמספר הברקוד של הבקרוד W109678 במסך שודרג בהצלחה, תוכל לבדוק למה?
![image](https://user-images.githubusercontent.com/119286016/205603612-9ec00d34-95a7-4143-8f96-5b652673ffe7.png)

**Comment by noam-honig** [comment]
ניתן למצוא את התשובה במסך מחשבים, מצא את הברקוד ובחץ ליידו בחר "שינויים"

שם תראה את ההשתלשלות של הסטטוסים של המחשב הזה.
מה שקרה איתו זה שעודכן לו סטטוס שודרג, ואז שוייך ואז שוב שודרג - ולכן הוא מופיע פעמיים כשודרג.

![image](https://user-images.githubusercontent.com/16635859/205614249-147fdb7b-e8fe-4163-b277-f6e3024e8a59.png)

**Comment by operationsmitchashvim** [comment]
הי,
הבנתי, תודה רבה על ההסבר.
איך מונעים זאת?

**Comment by noam-honig** [comment]
אני חושב שכדאי שתדבר עם זה עם שירה ותחליטו ביחד מה עושים מבחינת התהליך
