### ISSUE TITLE
נתונים במסך התקבל נייד שלא נשמרים

### ISSUE THREAD

**Issue by operationsmitchashvim** [noam-honig/mithashvim-maabada#38]
לק"י
נועם שלום,
בעת עבודה על כמות של מחשבים ניידים לדוגמא 30-50 מאותו:  דגם, יצרן, חברת שינוע, מקור תרומה, בר קוד משטח, נרצה לעבוד בצורה קבועה  על אותם נתונים ולא כל פעם להקליד את המידע מחדש באחד השדות, אלא רק לשנות את בר קוד של המחשב, איך ניתן לשמר את זה?
![image](https://user-images.githubusercontent.com/119286016/206893735-306a6d82-3be4-44b1-bb42-ee41c574a52e.png)

בתודה
גבריאל

**Comment by noam-honig** [comment]
כיום מקור תרומה כבר מועתק.
הוספתי את הסדות האחרים זה יהיה באויר עוד 5 דק

**Comment by operationsmitchashvim** [comment]
תבורך
