### ISSUE TITLE
משטח לא עובר למצב של עבר לממתין לשינוע למוטב

### ISSUE THREAD

**Issue by operationsmitchashvim** [noam-honig/mithashvim-maabada#39]
לק"י
נועם שלום,
יש לנו בעיה עם העברת משטח אל סטאטוס ממתין לשינוע למוטב, ניסית לבצע על בר קוד משטח Z6008
![image](https://user-images.githubusercontent.com/119286016/206894823-0c9b67ca-54a9-4396-83f7-f453ccac9905.png)

**Comment by noam-honig** [comment]
בוצע - יהיה באויר עוד 5 דק
