### ISSUE TITLE
למזג את הפרוייקט של FORMS לתוך הפרוייקט הזה

### ISSUE THREAD

**Issue by noam-honig** [noam-honig/mithashvim-maabada#4]
יש למזג את הפרוייקט https://github.com/noam-honig/mithashvim-forms לפרוייקט הזה, כך ששניהם יהיו באתר אחד (שלא יצטרכו לשלם עם שני אתרים)
ואז כל יכולות הMONDAY תהיינה כאן ויהיה יותר קל לעשות את הבחירה של מקור ושל מוטב מMONDAY.

- [ ] סעיף 12 בצופה ומביט - בחירת מוטב מBOARD 2478134523 בMONDAT
- [ ] סעיף 13 בצופה ומביט - בחירת מקור התרומה מ BOARD 2673923561 ב MONDAY

**Comment by shiraluk** [comment]
Closing
