### ISSUE TITLE
לא לאפשר למחשב שלא שיוך לעובד לעבור למצב שודרג בהצלחה

### ISSUE THREAD

**Issue by operationsmitchashvim** [noam-honig/mithashvim-maabada#40]
לק"י
נועם שלום
כרגע עובד יכול לעשות טעות ולא לשייך לעצמו מחשב ולאחר מכן להעביר אותו למסופון של שודרג בהצלחה ובדרך זו לא יודעים לשייך את המחשב לעובד.
אודה לך אם תוכל למנוע מהעובדים להעביר בר קוד למצב שודרג בהצלחה כאשר המחשב לא שיוך לעובד
בתודה
גבריאל

**Comment by noam-honig** [comment]
בוצע

**Comment by operationsmitchashvim** [comment]
יברך ה' מציון
תודה רבה!
