### ISSUE TITLE
שיוך לעובד לא נכון

### ISSUE THREAD

**Issue by operationsmitchashvim** [noam-honig/mithashvim-maabada#41]
לק"י
נועם שלום,
קיבלתי פנייה מרש"צ השדרוג שאתמול 13.12.2022 כלל השדרוג במערכת בוצעו על ידי עובד בשם יובל, ומשם מה רשום במערכת שגם עובד בשם יצחק שדרג מחשבים, תוכל לבדוק את זה
![image](https://user-images.githubusercontent.com/119286016/207299283-872cd4e3-f7b5-4ed7-bb06-5a898826ac18.png)

זה יתכן שנגרם מהמערכת או שפשוט הרש"צ לא עדכן במסופון את השם הנכון?

גבריאל

**Comment by noam-honig** [comment]
השיוך לעובד נעשה במסופון שיוך לעובד.
תבדוק בהיסטוריית שינוים של המחשב אם אתה רוצה עוד פרטים
