### ISSUE TITLE
הופעה של תורם לאחר שכבר בוצע קליטה

### ISSUE THREAD

**Issue by operationsmitchashvim** [noam-honig/mithashvim-maabada#42]
לק"י
במסך קליטת מחשב נייח  ונייד, מופיע שם התורם **כבאות והצלחה מחוז יו"ש** למרות שכבר מנהל המלאי ביצע קליטה למחשבים של כבאות והצלחה מחוז יו"ש.
שמתי לב במאנדיי שהכמות שהתורם היה אמור לספק היתה 10 נייחים, בפועל נמשכו 5 מחשבים נייחים ו-5 מחשבים ניידים וגם נקלטו במערכת צופה ומביט
ניסתי לאזן את זה במאנדי אבל הדבר לא התאפס בחלון של הקליטה ועדיין שם התורם מופיע  במקום לא הופיע שם.
נועם תוכל לבדוק את הלוגיקה.

חנוכה שמח!
גבריאל

**Comment by noam-honig** [comment]
במקרה הזה אתה צריך לעדכן ידנית בMONDAY את הסטטוס ספירת מלאי לסטטוס שאתה רוצה - 
![image](https://user-images.githubusercontent.com/16635859/208894007-c6f955ed-a81b-4f42-895c-2be012bd4d4e.png)

כלומר נקלט במפעל

**Comment by operationsmitchashvim** [comment]
100%
תודה רבה
