### ISSUE TITLE
ניקוי מסך קליטה במידה ואין מחשבים נייחין או ניידים

### ISSUE THREAD

**Issue by operationsmitchashvim** [noam-honig/mithashvim-maabada#43]
לק"י
נועם שלום,
קיבלנו תרומה של **קמהדע**  הסכום של המסכים אצל התורם, נהג, מנהל מלאי תקינה.
מכוון שבתרומה זו לא הגיעה בפועל(לא מופיע בעמודה של הנהג) מחשבים נייחים או ניידים נדרש לייצר מנגהון  להוריד את התורם ממסך הקליטה לאחר ביצעו הספירה של ידי מנהל המלאי במשקם(כנ"ל ביתר המקרים בהם סוגי התרומות אינם מכילים מחשבים נייחים או ניידים).
בתודה
גבריאל

**Comment by noam-honig** [comment]
תיקנתי שמעכשיו אם בספירת מלאי אין מחשבים, אז הסטטוס ספירת מלאי יעבור לירוק ולא יופיע במסך של קליטת מחשבים.

עבור הרשומה הספציפית הזו תעדכן את הסטטוס ספירת מלאי שלה לסטטוס הירוק כדי שהיא לא תופיע במסך קליטה

**Comment by operationsmitchashvim** [comment]
מעולה תודה רבה
