### ISSUE TITLE
תרומת מחשבים ניידיםשל חברת נטפים  עדיין מופיעה בחלון קליטה

### ISSUE THREAD

**Issue by operationsmitchashvim** [noam-honig/mithashvim-maabada#44]
לק"י
נועם שלום,
התקבלה תרומה של מחשבים ניידים מחברת **נטפים**, מבחינת ספירת ציוד וקליטה הכול בר בסדר.
תוכל לבדוק למה עדיין שם התורם מופיע במסך הקליטה?

בתודה
גבריאל

**Comment by noam-honig** [comment]
תורם מופיע במסך קליטה כאשר הסטטוס ספירת ציוד שלו בMONDAY (השדה האחרון) שלו
הוא "נספר וממתין לקליטה"
אם אתה רוצה שמשהו לא יופיע במסך קליטה, פשוט תבחר סטטוס אחר

במקרה של נתפים - נראה שהכמות בספירת מלאי נספרה על מחשב נייד - ואילו ניקלטה
במשקם כמחשב נייח

![image](https://user-images.githubusercontent.com/16635859/208892718-f5d7654b-2c8f-44f4-8a49-1693a0255f8e.png)

**Comment by noam-honig** [comment]
תורם מופיע במסך קליטה כאשר הסטטוס ספירת ציוד שלו בMONDAY (השדה האחרון) שלו
הוא "נספר וממתין לקליטה"
אם אתה רוצה שמשהו לא יופיע במסך קליטה, פשוט תבחר סטטוס אחר

במקרה של נתפים - נראה שהכמות בספירת מלאי נספרה על מחשב נייד - ואילו ניקלטה
במשקם כמחשב נייח

![image](https://user-images.githubusercontent.com/16635859/208892849-1c1d8ac1-41fe-43ff-9473-d08abac0b85a.png)

**Comment by operationsmitchashvim** [comment]
הי נועם,
ראשית תודה על ההסבר המעמיק איך לשנות ידנית את הבסטאטוס ב MONDAY על מנת למנוע הצגתו ב "צפוה ומביט"
שנית האבחנה שלך לא נכונה הקליטה היתה על ניידים ולא על נייחים, תוכל בבקשה לבדוק שוב
![image](https://user-images.githubusercontent.com/119286016/208973394-72fd3fb8-162a-42dd-b252-5a7ccc804aa2.png)

**Comment by noam-honig** [comment]
מצאתי את התקלה ותיקנתי אותה - תבדוק שוב?

**Comment by operationsmitchashvim** [comment]
לק"י
נועם שלום,
עדיין רואים את נטפים, למרות שהתחברתי מחדש מספר פעמים
![image](https://user-images.githubusercontent.com/119286016/209081745-50b03555-a321-43ab-ba7c-9baab4015225.png)

**Comment by noam-honig** [comment]
בבקשה לך לאחד המחשבים משם - או כנס לרשימה של נטפים ספציפית - ואז באחת
השורות תבחר "רענון נתונים בMONDAY"

https://mitchashvim-labs.herokuapp.com/%D7%A8%D7%A9%D7%99%D7%9E%D7%94%20%D7%9E%D7%AA%D7%A8%D7%A2%D7%A0%D7%A0%D7%AA?originId=3664620792
