### ISSUE TITLE
סיכום של מחשבים שהתקבלו ומחשבים שהתקבלו לגריטה 

### ISSUE THREAD

**Issue by operationsmitchashvim** [noam-honig/mithashvim-maabada#45]
לק"י
נועם שלום,
במסך התקבל מופיע התורם כללית באר שבע.
בפועל סופקו 88 מחשבים
62 ההתקבלו
26 התקבלו ועברו לגריטה.
בפועל המסך התקבל ממשיך להציג  את התורם למרות שהוא היה כבר צריך להסיר אותו מהתוצגה בשלב זה
תוכל לבדוק מדוע?
גבריאל

**Comment by noam-honig** [comment]
נראה שהיתה כאן בעיה בעדכון לMONDAY - אני חושב שתיקנתי אבל בכל מקרה שאתה רואה נתון בMONDAY שלא תקין ביחס למערכת אתה יכול לבקש מהמערכת לעדכן עבורו אותה תרומה את הסטטיסטיקות על ידי:
 לחיצה על החץ ליד השורה של מחשב מהתרומה הזו ולבחור "רענון נתונים בMONDAY"


החל מעוד 10 דק :)

**Comment by operationsmitchashvim** [comment]
הי נועם,
ראשית בצופת ומביט בחלון התקבל עדיין שם התורם לא נעלם תוכל לבדוק למה?
שנית "לחיצה על החץ ליד השורה של מחשב מהתרומה הזו ולבחור "רענון נתונים בMONDAY"
איפה זה נמצא?

**Comment by noam-honig** [comment]
תבדוק בבקשה מה הסטטוס ספירת מלאי של תורם זה במונדי.

את הרענון נתונים במונדי ניתן להפעיל במסך מחשבים או במסך רשימה מתרעמת. בחץ
בצד מימין  של השורה

**Comment by operationsmitchashvim** [comment]
הי 
הסאטוס הינו נספר וממתין לקליטה, מה שהוא לא נכון. אני לא רוצה להעביר את זה ידנית במאנדיי חשוב לי שזה יעבוד אוטומטית
![image](https://user-images.githubusercontent.com/119286016/208987858-6dea98ce-0f12-4955-8893-c47e7473900c.png)

**Comment by noam-honig** [comment]
ברור - גם אני רוצה שזה יעבוד אוטומטית, אבל הMONDAY שם לא תמיד מתעדכן בצורה
עקבית - אני עוד עוקב אחרי זה כדי להבין את המקור.

בינתיים כאשר אתה רואה אי התאמה, תרציץ במערכת את הרענון נתונים בMONDAY וזה
יפתור את הבעיה - (ככה פתרתי עכשיו)

בהצלחה

**Comment by noam-honig** [comment]
פתחתי שאלה לMONDAY בנושא - בוא נראה מה הם אומרים

https://community.monday.com/t/graphql-mutation-change-column-value-doesnt-allways-update-and-return-undefined-result-intermittently/47765

**Comment by operationsmitchashvim** [comment]
לק"י
הבנתי, יפה זכינו לאתגר אותם :)
