### ISSUE TITLE
הגדרת מוטב רלוונטי במסך 

### ISSUE THREAD

**Issue by operationsmitchashvim** [noam-honig/mithashvim-maabada#46]
לק"י
נועם שלום,
במסופון **ממתין לשינוע למוטב**    מנהל המלאי נדרש לבחור במוטב מתוך רשימת המוטבים שהגדרנו בתחילה למערכת מתוך ה- MONDAY
נדרש לנט לחדד בחירה זו על פי רשמית מוטבים מצמצת מתוך BOARD   **טבלת חלוקה 2022**
נדרש לייצר אפשרות בחירה רק מתוך רשימת המוטבים שיש להם סטאטוס שהוא **גם** שונה מסופק.

למה גם: כי יתכן שיש מספר הזמנות לאותו מוטב לאורך השנה.
נדרש לשים לב כי ב-2023 יפתח BOARD חדששגם אותו נדרש לשכלל בפיצ'ר זה
אודה לסיועך
גבריאל

**Comment by noam-honig** [comment]
בוצע - אנא בדוק עוד 5 דק

**Comment by operationsmitchashvim** [comment]
מעולה, תודה רבה.
תוכל לבדוק שיש לזה רק השפעה במסך זה ואין לזה השפעה על מסכים אחרים, מכיוון שמסך מחשבים הוא לא נתן לי לבחור שם של תורמים אחרים

**Comment by noam-honig** [comment]
Fixed - check in 5 minutes
