### ISSUE TITLE
העתקת כמויות של "מחשב נייד", "מחשב נייח" ו"מסך" מהסאב-אייטמס לתוך עמודות בטבלת השינוע

### ISSUE THREAD

**Issue by shiraluk** [noam-honig/mithashvim-maabada#47]
היום שירז ממתחשבים משתמשת במאנדיי כדי להפיק אישורי תרומה.
עבור אישורי התרומה היא צריכה במאנדיי יכולת לסכום רק את הכמויות של הפריטים הספציפיים = מחשב נייד, מחשב נייח, מסך
כרגע הכמויות האלה מופיעות כסאב אייטם, ובגלל מגבלה של מאנדיי לא ניתן לסכום אותם 

הפתרון שחשבנו עליו זה ליצור 3 עמודות חדשות בטבלת השינוע, אחת לכל סוג פריט
 כאשר הנהג מעדכן את הכמויות בפועל, באפליקציית הנהגים, צריך להסיק מבין האייטמים שעודכנו מה הכמות של כל מחשב נייד, מחשב נייח, מסך, ולעדכן בעמודות של הטבלה

**Comment by noam-honig** [comment]
Done
