### ISSUE TITLE
נטפים

### ISSUE THREAD

**Issue by operationsmitchashvim** [noam-honig/mithashvim-maabada#48]
לק"י
נוע שלום,
איך אני משנה את הקליטה של נטפים ממחשב נייח לנייד אחרי שכבר המחשבים במחערכת?
גבריאל

**Comment by noam-honig** [comment]
במסך מחשבים אתה יכול לעדכן את השדה מחשב נייד ולשמור

**Comment by operationsmitchashvim** [comment]
תודה, אני לא יכול. כי המידע לא זמין לי בצופה ומביט...אם אני מחפש נטפים אני מקבל כלום...
![image](https://user-images.githubusercontent.com/119286016/212564707-b3efb518-abde-4d1a-bbe4-3f8415822e9d.png)

**Comment by noam-honig** [comment]
תנסה לחפש לפי originid - עם המספר של המשלוח שרצית

**Comment by operationsmitchashvim** [comment]
אין כלום....המערכת המאנדיי וגם הצופה ומבי לא מציגות כלום.........מהו השתבש
קח לדוגמא איסוף שנחתם על ידי הנהג ואיש הקשר
![image](https://user-images.githubusercontent.com/119286016/212565791-1126da79-5a23-46c6-b7c0-f3e39b1c9fa1.png)

**Comment by noam-honig** [comment]
נראה שיש לכם סלט של נתונים בMONDAY - נעשה כנראה איזה תהליך שכפול ב10 לינואר שעשה לכם בלאגן.
אפשר לראות ברשומות הללו כמה דברים לא תקינים - העיקרי ביניהם הוא שתאריך קבלת המידע מופיע כל 10 לינואר. בהמשך אפשר לראות 11 פריטים ולא 7 כמו שאמור להיות, והכל נקרא COPY.

אם תלחץ על OPEN ליד השורה - תראה את הפרטים ואת הACTIVITY LOG שתוכל לראות שנעשה שם שכפול  ומי עשה.

אקיצר - לא קשור לצופה ומביט - זה פשוט בלאגן בMONDAY.

![image](https://user-images.githubusercontent.com/16635859/212608220-d2374ea6-e71d-4f57-a3df-4acb13484548.png)
