### ISSUE TITLE
המידע  על האיסופים של  2022 נעלם מהמערכת

### ISSUE THREAD

**Issue by operationsmitchashvim** [noam-honig/mithashvim-maabada#49]
לק"י
נועם שלום,
שוב!
המידע של האיסוף נעלם מהמערכת, היה איסוף לדוגמא של נטפים ....כל המידע לגביהם נעלם.
![image](https://user-images.githubusercontent.com/119286016/212564087-6e6129df-4dc6-4edc-99ea-b2d56773b018.png)
![image](https://user-images.githubusercontent.com/119286016/212564097-bec4f9d2-0c72-4c46-a012-7762b9789026.png)

מה עושים? מרגיש לי שמישהו מתיש אותנו
גבריאל

**Comment by operationsmitchashvim** [comment]
לק"י
נועם בוקר טוב, אודה לך אם תוכל לבדוק את הדבר בהקדם

**Comment by noam-honig** [comment]
בבקשה שלח לי במייל אן בהודעה את הI’d של משלוחים שלא עובדים לך.
גם אם נראה שזה כולם - שלח לי ארבע

**Comment by noam-honig** [comment]
ראה תשובה ל#48 - זו אות התשובה
