### ISSUE TITLE
הודעה כאשר מעדכנים את אותו הסטטוס למחשב

### ISSUE THREAD

**Issue by noam-honig** [noam-honig/mithashvim-maabada#5]
מחשב בסטטוס "ממתין לגריטה" ו"ממתין לשדרוג" ( וגם "שודרג בהצלחה" וגם "ממתין לאריזה") ניתן להזנה מחדש מבלי שהמערכת מתריעה על כך. צריך ליצור הודעת שגיאה כזו, כמו שיש במסכים האחרים  

כלומר - כאשר מעדכנים מחשב לאותו הסטטוס בוא הוא כבר נמצא - לתת הודעה

**Comment by shiraluk** [comment]
Closing
