### ISSUE TITLE
המידע בקשר למחשבים הניידים לא מתעדכן בדשבורד

### ISSUE THREAD

**Issue by operationsmitchashvim** [noam-honig/mithashvim-maabada#50]
לק"י
נועם שלום,
המידע בגין קליטה וגריטה של מחשבים ניידים אינו מתקבל בדשבורד תוכל לבדוק למה?
החשיבות של טיפול בדבר נכון לרגע זה פחות דחופה, יותר דחוף לי לטפל בתקלה השניה

![image](https://user-images.githubusercontent.com/119286016/212598731-3fb384dd-8323-479f-874a-9536aa7dce52.png)

**Comment by noam-honig** [comment]
כל המחשבים הניידים נמצאים כעת בסטטוס ממתין לשדרוג (ראה מסך מחשבים, סינון על מחשב נייד = TRUE)

**Comment by noam-honig** [comment]
אולי יש טעם לחלק את המסך הזה לשתי עמודות - נייחים וניידים.

**Comment by operationsmitchashvim** [comment]
> כל המחשבים הניידים נמצאים כעת בסטטוס ממתין לשדרוג (ראה מסך מחשבים, סינון על מחשב נייד = TRUE)
קיבלתי, תודה רבה

**Comment by operationsmitchashvim** [comment]
> אולי יש טעם לחלק את המסך הזה לשתי עמודות - נייחים וניידים.

תוכל לעשות זאת?,

**Comment by operationsmitchashvim** [comment]
נועם, מה אומר?

**Comment by noam-honig** [comment]
סבבה

**Comment by operationsmitchashvim** [comment]
תוכל להפריד בין המחשבים הנייחים לניידים בשתי טבלאות?

**Comment by noam-honig** [comment]
כבר בוצע :)

**Comment by operationsmitchashvim** [comment]
איפה עיוני?
![image](https://user-images.githubusercontent.com/119286016/215317222-e848cb31-a71d-47ed-88d3-bffa0c5376cd.png)

**Comment by noam-honig** [comment]
יש עמודת מחשבים ועמודת ניידים

**Comment by operationsmitchashvim** [comment]
אוי ואבוי....אני צריך לחזור לישון, פיספסתי את זה.

תודה גבריאל
