### ISSUE TITLE
סטטוסים חדשים במערכת - "ממתין לשינוע למעבדת כפר סבא", "ממתין לשינוע למחסני סנטורי"

### ISSUE THREAD

**Issue by shiraluk** [noam-honig/mithashvim-maabada#52]
רוצים לתמוך בעוד שני סטטוסים חדשים, שמקבילים לסטטוס הקיים של "ממתין לשינוע לארכיברים":
1. "ממתין לשינוע למעבדת כפר סבא"
2. "ממתין לשינוע למחסני סנטורי"

כיום יש מסופון שמשנה את הסטטוס של "ממתין לשינוע לארכיברים":

![Image](https://user-images.githubusercontent.com/10912057/212867611-acce97f5-b569-4631-a411-7f42555351d5.png)

אני רואה שתי אפשרויות למימוש, תלוי מה שיהיה לך הכי נוח - 

1. לשכפל את המסופון הקיים, ולהוסיף עוד שני מסופונים - אחד לכל סטטוס חדש
2. לשנות את השם של המסופון הקיים ל"ממתין לשינוע בין מעבדות / מחסנים" ולשים דרופדאון שבו המשתמש יבחר את היעד הנכון משבין שלושת היעדים. עדכון במסופון ישנה את הסטטוס של המחשבים בהתאם.

**Comment by noam-honig** [comment]
מי מהם מחליף את הממתין לשינוע הנוכחי?

**Comment by noam-honig** [comment]
בוצע

**Comment by operationsmitchashvim** [comment]
מלך!

תודה
