### ISSUE TITLE
כשמחשב עובר לססטוס "שודרג בהצלחה" - יש לעדכן את בורד "מלאי" במאנדיי

### ISSUE THREAD

**Issue by shiraluk** [noam-honig/mithashvim-maabada#53]
יש לעדכן את השורה שנקראת "סה"כ דיסקים", בעמודה שנקראת "כמות במשקם", ולחסר מהמספר שלה 1

![Image](https://user-images.githubusercontent.com/10912057/213392234-c27d0b75-2ddb-46ad-9803-687ff17a5d8f.png)

**Comment by noam-honig** [comment]
Done

**Comment by shiraluk** [comment]
גבריאל כרגע לא יכול לוודא שזה אכן קורה.
בר יבצע בדיקה בעתיד ויעדכן אם יש בעיות.
כרגע אנחנו סוגרים את האישו
