### ISSUE TITLE
כשמחשב עובר לסטטוס "תהליך אריזה" - יש לעדכן את בורד "מלאי" במאנדיי

### ISSUE THREAD

**Issue by shiraluk** [noam-honig/mithashvim-maabada#54]
יש לעדכן את השורות הבאות, בעמודה "כמות במשקם", ולחסר 1

כתלות בסוג המקלדת, יש לעדכן את השורה הנכונה מבין - 
סט מקלדת עברית + עכבר
מקלדות חוטי בלבד בערבית

ובנוסף יש לעדכן את השורות - 
אוזניות
מצלמות
דונגלים
סט כבלים משולב
אריזות קרטון

![Image](https://user-images.githubusercontent.com/10912057/213398247-cdcd2e1f-bc40-427f-a037-0942e50687dd.png)

**Comment by noam-honig** [comment]
נראה לי מוזר לעשות מלאי בצורה הזו - בתי תנועות מסודרות, כניסה יציאה וכו...

בכל מקרה - יש גם מחשבים ניידים - הנתונים הללו נכונים גם להם?

**Comment by operationsmitchashvim** [comment]
לגבי המחשבים הניידים יש לקזז דיסק 1 מהמלאי לאחר שהמחשב עבר שדרוד

**Comment by shiraluk** [comment]
גבריאל כרגע לא יכול לוודא שזה אכן קורה.
בר יבצע בדיקה בעתיד ויעדכן אם יש בעיות.
כרגע אנחנו סוגרים את האישו
