### ISSUE TITLE
כשמשטח עובר לאחד מהסטטוסים מסוג "ממתין לשינוע" - יש לעדכן את בורד "מלאי" במאנדיי

### ISSUE THREAD

**Issue by shiraluk** [noam-honig/mithashvim-maabada#55]
זה יכול לקרות באחד מארבעת המסופונים, רק כאשר שיטת העדכון היא "עדכן משטח"

המסופונים הם:

![Image](https://user-images.githubusercontent.com/10912057/213394519-9d462060-75d8-49ad-bc7e-b5248c5a6694.png)

והתא שצריך לעדכן הוא בשורה "משטחים ריקים", בעמודה "כמות במשקם", צריך לחסר 1

![Image](https://user-images.githubusercontent.com/10912057/213394746-ca306f79-3232-42ba-88f2-bf53f18d92de.png)

**Comment by noam-honig** [comment]
done

**Comment by shiraluk** [comment]
גבריאל לא יכול לבדוק כרגע האם זה עובד בשטח, אבל מבחינתנו אפשר לסגור את האישו
