### ISSUE TITLE
מסופון "תהליך אריזה" - יש להוסיף דרופדאון של סוג המקלדת

### ISSUE THREAD

**Issue by shiraluk** [noam-honig/mithashvim-maabada#56]
כותרת הדרופדאון:
"סוג מקלדת"

ערכים:
"עברית/אנגלית"
"ערבית/עברית/אנגלית"

ככה - 

![Image](https://user-images.githubusercontent.com/10912057/213396613-7218001d-1e3c-4200-8dae-b4f2cd86033e.png)

הדרופדאון ישמור את הערך הבחור גם אחרי שהיוזר עשה עדכון

סוג המקלדת צריך להופיע גם כעמודה חדשה בטבלת המחשבים, כדי שהם יוכלו לדעת כמה מחשבים הגיעו לכל מגזר

**Comment by noam-honig** [comment]
בוצע

**Comment by operationsmitchashvim** [comment]
תודה רבה
