### ISSUE TITLE
כפילות

### ISSUE THREAD

**Issue by operationsmitchashvim** [noam-honig/mithashvim-maabada#57]
לק"י
נועם שלום,
תוכל לבדוק למהיש כפילות במסך
![image](https://user-images.githubusercontent.com/119286016/213985744-887b0969-ae6e-477c-a120-c046d456fda2.png)

**Comment by noam-honig** [comment]
נא לבדוק במונדי :)

**Comment by operationsmitchashvim** [comment]
אני לא רואה במקרה זה כפילות
![image](https://user-images.githubusercontent.com/119286016/213993277-320ef2b4-59cb-414d-a713-a6f429357dad.png)

**Comment by noam-honig** [comment]
מעניין - שים לב שכתוב שיש 10 ITEMS וזה רק מציג שלש - יש לך מושג למה?

**Comment by operationsmitchashvim** [comment]
מעניין - שים לב שכתוב שיש 10 ITEMS וזה רק מציג שלש - יש לך מושג למה?

גררררררר...שירז...אני הולך לשים לה השבוע בארוחת הצהרים הרבה חריף בפיתה

**Comment by operationsmitchashvim** [comment]
צודק טיפלתי
