### ISSUE TITLE
תוספת שורה להערה

### ISSUE THREAD

**Issue by operationsmitchashvim** [noam-honig/mithashvim-maabada#58]
לק"י
נועם שלום,
אבקש להוסיף שורה של הערה: למלל חופשי(כדי שמנהל המלאי יוסיף הערה בעת בעיה) בתחתית הטבלה של חלון" ספירת ציוד מתרומה", נדרש למקם את מקום הערה בין הטבלה לבין הכפתור של עדכן.
![image](https://user-images.githubusercontent.com/119286016/213987974-bc5be2c8-7d8d-4faf-90c2-d462f27a3f79.png)

בתודה
גבריאל

**Comment by noam-honig** [comment]
DONE

**Comment by operationsmitchashvim** [comment]
תודה רבה!
