### ISSUE TITLE
טבלת הסכימה נעלמה

### ISSUE THREAD

**Issue by operationsmitchashvim** [noam-honig/mithashvim-maabada#59]
לק"י 
נועם שלום 
בחלון של קליטת  וגריטת הציוד הטבלאות של הסכימה של מה שנקלט בעבר(בצד השמאלי של המסך) נעלמו משום מה
![image](https://user-images.githubusercontent.com/119286016/213996383-f0c4a896-50f8-4771-a4df-3002f66f5b55.png)

![image](https://user-images.githubusercontent.com/119286016/213996432-2af0fe99-fb15-4efc-877b-3f409e6e3d1e.png)

**Comment by operationsmitchashvim** [comment]
מה אומר?

**Comment by noam-honig** [comment]
תוקן

**Comment by operationsmitchashvim** [comment]
תודה רבה
