### ISSUE TITLE
הוספת כיתוב במסך הראשי

### ISSUE THREAD

**Issue by operationsmitchashvim** [noam-honig/mithashvim-maabada#60]
לק"י
נועם שלום,
תוכל בבקשה להוסיף את הכיתוב הבא במסך הראשי של המערכת:
![image](https://user-images.githubusercontent.com/119286016/214681806-26d831a8-22d2-4452-ab91-c9ba1581fd92.png)

![image](https://user-images.githubusercontent.com/119286016/214681354-112f3f1c-bd46-4d47-890f-bae4868f7d76.png)

**Comment by noam-honig** [comment]
Done

**Comment by operationsmitchashvim** [comment]
ראשית תודה על המענה המהיר.
שנית האם אפשר להוריד את זה בשתי שורות מטה ושלא יהיה דבוק לראש המסך?
![image](https://user-images.githubusercontent.com/119286016/214934304-6b533973-a518-4eb4-be2f-065bc49e5197.png)

**Comment by noam-honig** [comment]
DONE
