### ISSUE TITLE
היזון חוזר על קליטת מחשבים אל מול מחשבים שעוברים לגריטה

### ISSUE THREAD

**Issue by operationsmitchashvim** [noam-honig/mithashvim-maabada#61]
לק"י
נועם שלום,
ב-8 לינואר נספרה ונקלטה תרומה של העמותה להנצחת חללי הקשר והתקשוב היא הוזנה בצופה ומביט. על פי הכמויות הדבר תקין.
בדקתי בצופה ומביט מתוך 8 משחשבים נייחים 3 עברו לגריטה .
למה הדבר לא מוצג במאנדיי, ש-3 נקלטו לגריטה והכמות היא 0?
יכול להיות שאני מפספס משהו? שירה?
גבריאל
![image](https://user-images.githubusercontent.com/119286016/214686624-10e61dab-36f0-4c5e-a353-a86028d49b2f.png)

**Comment by noam-honig** [comment]
אכן היתה תקלה - תיקנתי אותה ומעכשיו והלאה זה יעדכן תקין.

כדי לתקן עבור שורות קיימות, יש לבחור את האופציה הבאה ליד אחד ממחשבי משלוח עם תקלת נתונים:
![image](https://user-images.githubusercontent.com/16635859/214807491-ba69c23c-ae88-4dd3-906d-7c7b2b3f3a35.png)

**Comment by operationsmitchashvim** [comment]
תודה רבה!
