### ISSUE TITLE
כפילות תורמים בחלון ספירת ציוד מתרומה

### ISSUE THREAD

**Issue by operationsmitchashvim** [noam-honig/mithashvim-maabada#62]
לק"י
נועם שלום,
בחלון ספירת ציוד מתרומ האם אני בוחר תורם אחד אני יכול לראות את הפרטים שלו, במידה ואני רק **משנה**  בחלון זה את שם התורם **בלי לבצע עדכון**,  אני מקבל את השם של התורם בחלון העליון....אבל רשימה   משתנית ומכילה את רשימת הציוד של שני התורמים, ראשון והשני.
תוכע למנוע זאת
מצ"ב דוגמא לכך שבחרתי את  BONDIT ואת אקים  אחד אחרי השני...
![image](https://user-images.githubusercontent.com/119286016/215325064-ba16cadb-84d2-4a97-ac2b-08d650da750b.png)
![image](https://user-images.githubusercontent.com/119286016/215325083-0dd6652e-6ec4-4611-8d52-0d9e9d2d2f0d.png)

גבריאל

**Comment by noam-honig** [comment]
בוצע

**Comment by operationsmitchashvim** [comment]
ה' יברך אותך

**Comment by operationsmitchashvim** [comment]
ה' יברך אותך
